---
- name: Add bitnami chart repo
  community.kubernetes.helm_repository:
    state: present
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy postgresql
  community.kubernetes.helm:
    state: "{{ postgresql_state }}"
    name: postgresql
    namespace: "{{ postgresql_namespace }}"
    # 会自动创建k8s的ns
    create_namespace: true
    chart_ref: bitnami/postgresql
    chart_version: 10.3.13
    values: "{{ lookup('template', 'postgresql_values.yml.j2') | from_yaml | combine(postgresql_chart_values, recursive=True) }}"
    wait: yes
    wait_timeout: 10m
  register: postgresql_installed
